#!/home/nosy/.juliaup/bin/julia

# let julia handle the git pushes

using ArgParse

function parse_commandline()
   s = ArgParseSettings()

   @add_arg_table s begin
      "--site"
         help="the site to be pushed. defaults to <root>"
         default=""
      "--msg"
         help="the commit message. defaults to <up>"
         default="up"
   end

   parse_args(s)
end


function pushit(msg)
   run(pipeline(`git add --all`))
   run(pipeline(`git commit -m "$(msg)"`))
   run(pipeline(`git push origin master`))
end


if abspath(PROGRAM_FILE)==@__FILE__
   clargs = parse_commandline()
   site = clargs["site"]
   msg = clargs["msg"]

   println()
   @info "pushing the <root>\n"
   pushit(msg)
   if site>""
      println()
      @info "pushing the site <$(site)>\n"
      cd(joinpath(site,"__site"))
      @info "pwd is: $(pwd())"
      pushit(msg)
   end
end
